version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
    volumes:
      - .:/result_system
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - "TZ=Japan"
