docker:
  - image: circleci/ruby:2.5.1  # language image
    environment:
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      BUNDLE_PATH: vendor/bundle
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
  - image: circleci/postgres:9.5-alpine  # service image
    environment:
      POSTGRES_USER: circleci-demo-ruby
      POSTGRES_DB: rails_blog
      POSTGRES_PASSWORD: ""
